name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        python backend/manage.py test

# name: publish
# on: [push]
# jobs:
# publish-landboxpage:
# runs-on: ubuntu-latest
# steps:
# - uses: actions/checkout@v2
# - name: Login to GitHub Container Registry
# uses: docker/login-action@v1
# with:
# registry: ghcr.io
# username: ${{ github.actor }}
# password: ${{ secrets.GITHUB_TOKEN }}
# - name: Build the landbox-docker Docker image
# run: |
#        docker build . --tag ghcr.io/deltacodepl/landboxpage:latest
#        docker run ghcr.io/deltacodepl/landboxpage:latest
#        docker push ghcr.io/deltacodepl/landboxpage:latest
